import { Activity, BarChart3, Cpu, Radar, Search } from 'lucide-react';
const steps = [['Котировки', Search],['Импульс', Activity],['Индикаторы', BarChart3],['ML-фильтр', Cpu]];
export default function MarketAnalysisOverlay({ open, asset, timeframe }) {
  if (!open) return null;
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/78 px-5 backdrop-blur-md"><div className="w-full max-w-sm overflow-hidden rounded-lg border border-terminal-green/40 bg-terminal-card shadow-2xl">
    <div className="relative h-40 border-b border-terminal-border bg-terminal-bg"><div className="market-grid absolute inset-0" /><div className="market-scan absolute inset-x-0 top-0 h-16" /><div className="absolute inset-0 flex items-center justify-center"><div className="relative grid h-24 w-24 place-items-center rounded-full border border-terminal-green/40 bg-terminal-green/10"><span className="analysis-ring absolute inset-0 rounded-full border border-terminal-green/30" /><span className="analysis-ring absolute inset-3 rounded-full border border-terminal-green/20" /><Radar size={38} className="text-terminal-green" /></div></div></div>
    <div className="p-5"><div className="text-xs uppercase text-terminal-muted">Идет анализ рынка</div><div className="mono mt-1 text-2xl font-extrabold">{asset || 'Актив'}</div><div className="mt-1 text-sm text-terminal-muted">Таймфрейм: {timeframe || '...'}</div><div className="mt-5 space-y-3">{steps.map(([label, Icon], index) => <div key={label} className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-terminal-green/10 text-terminal-green"><Icon size={18} /></div><div className="flex-1"><div className="flex items-center justify-between text-sm"><span>{label}</span><span className="mono text-terminal-green">{index < 3 ? 'scan' : 'wait'}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-terminal-bg"><div className="analysis-progress h-full rounded-full bg-terminal-green" style={{ animationDelay: `${index * 180}ms` }} /></div></div></div>)}</div></div>
  </div></div>;
}
