import { X } from 'lucide-react';
import { useState } from 'react';

const timeframes = ['', '1m', '3m', '5m'];

export default function SessionModal({ open, onClose, onSubmit }) {
  const [goal, setGoal] = useState('50'); const [trade, setTrade] = useState('5'); const [timeframe, setTimeframe] = useState(''); const [loading, setLoading] = useState(false);
  if (!open) return null;
  async function submit(event) { event.preventDefault(); setLoading(true); try { await onSubmit({ goal_amount:Number(goal), trade_amount:Number(trade), timeframe_filter:timeframe || null }); onClose(); } finally { setLoading(false); } }
  return <div className="session-modal-backdrop fixed inset-0 z-[70] grid items-end bg-black/70 px-3"><form onSubmit={submit} className="session-modal-shell terminal-scroll w-full rounded-lg border border-terminal-border bg-terminal-card p-4 shadow-2xl"><div className="sticky top-0 z-10 -mx-4 -mt-4 flex items-center justify-between border-b border-terminal-border bg-terminal-card px-4 py-4"><h2 className="text-lg font-bold">Старт сессии</h2><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-md bg-terminal-hover"><X size={18}/></button></div><label className="mt-4 block text-sm text-terminal-muted">Цель прибыли ($)<input value={goal} onChange={e=>setGoal(e.target.value)} type="number" min="1" step="1" className="mt-2 w-full rounded-md border border-terminal-border bg-terminal-bg px-3 py-3 text-white"/></label><label className="mt-3 block text-sm text-terminal-muted">Сумма на сделку ($)<input value={trade} onChange={e=>setTrade(e.target.value)} type="number" min="1" step="1" className="mt-2 w-full rounded-md border border-terminal-border bg-terminal-bg px-3 py-3 text-white"/></label><label className="mt-3 block text-sm text-terminal-muted">Таймфрейм<select value={timeframe} onChange={e=>setTimeframe(e.target.value)} className="mt-2 w-full rounded-md border border-terminal-border bg-terminal-bg px-3 py-3 text-white">{timeframes.map(item=><option key={item||'all'} value={item}>{item||'Все'}</option>)}</select></label><button disabled={loading} className="mt-5 h-12 w-full rounded-md bg-terminal-green font-bold text-black disabled:opacity-50">{loading?'Запуск...':'Запустить'}</button></form></div>;
}
