import { Power, Target, TrendingUp } from 'lucide-react';
import { money } from '../utils/format';

export default function SessionPanel({ session, onStart, onEnd }) {
  const progress = session ? Math.min(100, Math.max(0, (Number(session.pnl) / Number(session.goal_amount)) * 100)) : 0;
  const winrate = session?.total_trades ? Math.round((session.wins / session.total_trades) * 100) : 0;
  function toggleSession(){ if(!session){onStart();return;} if(window.confirm('Завершить текущую сессию?')) onEnd(); }
  return <section className="border-b border-terminal-border bg-terminal-bg px-4 pb-4"><div className="rounded-lg border border-terminal-border bg-terminal-card p-4"><div className="flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-sm text-terminal-muted"><TrendingUp size={16}/><span>Сессия</span></div><div className="mt-1 text-2xl font-extrabold">{session?'Активна':'Остановлена'}</div></div><button type="button" onClick={toggleSession} className={`relative flex h-14 w-32 shrink-0 items-center rounded-full border p-1 transition ${session?'justify-end border-terminal-green bg-terminal-green/15 shadow-pulse':'justify-start border-terminal-border bg-terminal-bg'}`}><span className={`absolute ${session?'left-4':'right-4'} text-xs font-extrabold ${session?'text-terminal-green':'text-terminal-muted'}`}>{session?'ON':'OFF'}</span><span className={`grid h-12 w-12 place-items-center rounded-full ${session?'bg-terminal-green text-black':'bg-terminal-hover text-white'}`}><Power size={20}/></span></button></div>{session?<div className="mt-4 space-y-3"><div className="flex items-center justify-between text-sm"><span className="flex items-center gap-2 text-terminal-muted"><Target size={15}/> Цель: +${Number(session.goal_amount).toFixed(2)}</span><span className="mono text-terminal-green">{money(session.pnl)}</span></div><div className="h-2 rounded-full bg-terminal-bg"><div className="h-2 rounded-full bg-terminal-green" style={{width:`${progress}%`}}/></div><div className="grid grid-cols-4 gap-2 text-center text-xs"><Metric label="Сделок" value={session.total_trades}/><Metric label="WIN" value={session.wins} accent="text-terminal-green"/><Metric label="LOSS" value={session.losses} accent="text-terminal-red"/><Metric label="Winrate" value={`${winrate}%`}/></div></div>:<p className="mt-3 text-sm leading-6 text-terminal-muted">Сдвинь ползунок, чтобы начать сессию и отмечать WIN/LOSS.</p>}</div></section>;
}
function Metric({label,value,accent='text-white'}){return <div className="rounded-lg bg-terminal-bg px-2 py-2"><div className={`mono text-sm font-bold ${accent}`}>{value}</div><div className="mt-1 text-terminal-muted">{label}</div></div>}
