import clsx from 'clsx';
import { Check, Clock3, Star, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { countdown } from '../utils/format';

export default function SignalCard({ signal, disabled, marked, onMark }) {
  const [timer,setTimer]=useState(countdown(signal.expires_at)); const isPut=signal.direction==='PUT'; const directionLabel=isPut?'SELL':'BUY'; const entryTime=signal.entry_time?new Date(signal.entry_time+(signal.entry_time.endsWith?.('Z')?'':'Z')).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
  useEffect(()=>{const interval=window.setInterval(()=>setTimer(countdown(signal.expires_at)),1000);return()=>window.clearInterval(interval)},[signal.expires_at]);
  return <article className={clsx('rounded-lg border bg-terminal-card p-4 transition',marked==='WIN'&&'border-terminal-green',marked==='LOSS'&&'border-terminal-red',!marked&&'border-terminal-border hover:bg-terminal-hover',disabled&&!marked&&'opacity-60')}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h3 className="text-lg font-bold">{signal.asset}</h3><Star size={15} className="text-terminal-green"/></div><div className="mt-1 text-xs uppercase text-terminal-muted">{signal.asset_category} · {signal.timeframe}</div></div><div className={`rounded-md px-3 py-2 text-sm font-extrabold ${isPut?'bg-terminal-red/15 text-terminal-red':'bg-terminal-green/15 text-terminal-green'}`}>{directionLabel}</div></div><div className="mt-4 grid grid-cols-3 gap-2 text-sm"><Data label="Confidence" value={`${Math.round(signal.confidence*100)}%`}/><Data label="Вход" value={entryTime} mono/><Data label="Таймер" value={timer} mono/></div><div className="mt-3 text-xs text-terminal-muted">{signal.strategy||'—'} · {signal.market_regime||'—'}</div>{marked?<div className={`mt-4 flex items-center gap-2 rounded-md px-3 py-3 text-sm font-bold ${marked==='WIN'?'bg-terminal-green/10 text-terminal-green':'bg-terminal-red/10 text-terminal-red'}`}>{marked==='WIN'?<Check size={18}/>:<X size={18}/>}Отмечено: {marked}</div>:<div className="mt-4 grid grid-cols-2 gap-2"><button disabled={disabled} onClick={()=>onMark(signal.id,'WIN')} className="flex h-11 items-center justify-center gap-2 rounded-md bg-terminal-green font-bold text-black disabled:opacity-40"><Check size={17}/>WIN</button><button disabled={disabled} onClick={()=>onMark(signal.id,'LOSS')} className="flex h-11 items-center justify-center gap-2 rounded-md bg-terminal-red font-bold text-white disabled:opacity-40"><X size={17}/>LOSS</button></div>}{disabled&&!marked&&<div className="mt-3 flex items-center gap-2 text-xs text-terminal-muted"><Clock3 size={14}/>Дождись окончания cooldown.</div>}</article>;
}
function Data({label,value,mono=false}){return <div className="rounded-md bg-terminal-bg px-2 py-2"><div className="text-xs text-terminal-muted">{label}</div><div className={clsx('mt-1 truncate text-sm font-bold',mono&&'mono')}>{value}</div></div>}
