import { ArrowLeft, Check, Search, SlidersHorizontal } from 'lucide-react';
import { useMemo, useState } from 'react';
import { ASSETS, CATEGORY_META } from '../data/assets';

export default function AssetCategoryPage({ category, selectedAsset, onBack, onSelect, onSelectCategory }) {
  const [query, setQuery] = useState('');
  const meta = CATEGORY_META[category];
  const assets = ASSETS[category] || [];
  const filtered = useMemo(() => { const value = query.trim().toLowerCase(); if (!value) return assets; return assets.filter((asset) => asset.toLowerCase().includes(value)); }, [assets, query]);
  return <div className="pb-24"><header className="border-b border-terminal-border px-4 pb-4"><div className="flex items-center justify-between gap-3"><button type="button" onClick={onBack} className="grid h-11 w-11 place-items-center rounded-lg border border-terminal-border bg-terminal-card" title="Назад"><ArrowLeft size={20}/></button><div className="min-w-0 flex-1"><div className="text-xs uppercase text-terminal-muted">{meta.subtitle}</div><h1 className="truncate text-2xl font-extrabold">{meta.title}</h1></div><button type="button" onClick={() => onSelectCategory(category)} className="flex h-11 items-center gap-2 rounded-lg bg-terminal-green px-3 font-bold text-black"><SlidersHorizontal size={18}/>Все</button></div><label className="mt-4 flex h-12 items-center gap-2 rounded-lg border border-terminal-border bg-terminal-card px-3"><Search size={18} className="text-terminal-muted"/><input value={query} onChange={(event)=>setQuery(event.target.value)} placeholder="Найти актив" className="w-full bg-transparent text-base text-white outline-none placeholder:text-terminal-muted"/></label></header><main className="grid grid-cols-2 gap-3 px-4 py-4">{filtered.map((asset)=><AssetCard key={asset} asset={asset} meta={meta} selected={selectedAsset===asset} onClick={()=>onSelect(category,asset)}/>)}</main></div>;
}
function AssetCard({asset,meta,selected,onClick}) { const parts=asset.includes('/')?asset.split('/'):[asset,meta.title]; return <button type="button" onClick={onClick} className={`relative min-h-28 overflow-hidden rounded-lg border p-3 text-left transition ${selected?'border-terminal-green bg-terminal-green/12':'border-terminal-border bg-terminal-card hover:bg-terminal-hover'}`}><div className={`absolute inset-0 bg-gradient-to-br ${meta.tone}`}/><div className="relative flex items-start justify-between gap-2"><div className="grid h-10 w-10 place-items-center rounded-lg bg-black/30 text-xs font-extrabold text-terminal-green">{meta.short}</div>{selected&&<span className="grid h-7 w-7 place-items-center rounded-full bg-terminal-green text-black"><Check size={16}/></span>}</div><div className="relative mt-4"><div className="mono truncate text-lg font-extrabold">{asset}</div><div className="mt-1 text-sm text-terminal-muted">{parts[0]} / {parts[1]||meta.title}</div></div></button> }
