import { useCallback, useEffect, useState } from "react";

const API = window.location.origin;
const TG = window.Telegram?.WebApp;
const TG_ID = TG?.initDataUnsafe?.user?.id ?? null;
const PAIRS = ["EUR/USD","GBP/USD","USD/JPY","USD/CHF","AUD/USD","USD/CAD","NZD/USD","EUR/GBP","EUR/JPY","GBP/JPY"];
const TFS = ["1m","5m","15m","1h"];
const C={bg:"#0d1117",card:"#141824",card2:"#1a1f2e",border:"#232b3e",text:"#e8eaf6",muted:"#8892b0",accent:"#5c6bc0",accent2:"#3f51b5",green:"#00e5a0",red:"#ff4d6d",gold:"#f5c542"};
const box={background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:16};
const button={border:0,borderRadius:10,padding:"11px 14px",background:`linear-gradient(90deg,${C.accent2},${C.accent})`,color:"white",fontWeight:800,cursor:"pointer"};

function Badge({direction}){const buy=direction==="BUY";return <span style={{padding:"3px 9px",borderRadius:7,fontSize:12,fontWeight:800,color:buy?C.green:C.red,border:`1px solid ${buy?C.green:C.red}`,background:buy?"rgba(0,229,160,.1)":"rgba(255,77,109,.1)"}}>{buy?"BUY / CALL":"SELL / PUT"}</span>}
function Pill({children,color=C.accent}){return <span style={{fontSize:11,border:`1px solid ${color}`,color,borderRadius:20,padding:"2px 7px"}}>{children}</span>}
function SignalCard({s}){return <div style={{...box,marginBottom:10,background:`linear-gradient(135deg,${C.card},${C.card2})`}}>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:8}}><b>{s.pair}</b><div style={{display:"flex",gap:6,alignItems:"center"}}>{s.is_vip&&<Pill color={C.gold}>VIP</Pill>}<Pill>{s.timeframe}</Pill><Badge direction={s.direction}/></div></div>
  <div style={{height:6,background:C.card2,borderRadius:8,overflow:"hidden",margin:"10px 0 6px"}}><div style={{height:"100%",width:`${Math.min(100,s.confidence||0)}%`,background:(s.confidence||0)>=80?C.green:C.gold}}/></div>
  <div style={{display:"flex",justifyContent:"space-between",fontSize:12,color:C.muted}}><span>Confidence <b style={{color:C.text}}>{s.confidence}%</b></span>{s.result&&<span style={{color:s.result==="WIN"?C.green:s.result==="LOSS"?C.red:C.gold,fontWeight:800}}>{s.result}</span>}</div>
  {(s.strategy_label||s.strategy)&&<div style={{fontSize:12,color:C.muted,marginTop:8}}>Strategy: <b style={{color:C.text}}>{s.strategy_label||s.strategy}</b></div>}
  {s.entry_time&&<div style={{fontSize:12,color:C.muted,marginTop:4}}>Entry: <b style={{color:C.green}}>{new Date(s.entry_time).toLocaleTimeString()}</b>{s.expiry_time&&<> · Expiry: <b style={{color:C.text}}>{new Date(s.expiry_time).toLocaleTimeString()}</b></>}</div>}
  {s.reason&&<div style={{fontSize:12,color:C.muted,borderTop:`1px solid ${C.border}`,paddingTop:8,marginTop:8}}>{s.reason}</div>}
</div>}
function Selector({value,onChange,items}){return <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{items.map(x=><button key={x} onClick={()=>onChange(x)} style={{border:`1px solid ${value===x?C.accent:C.border}`,background:value===x?C.accent2:C.card2,color:value===x?"white":C.muted,borderRadius:8,padding:"6px 10px",fontSize:12,fontWeight:value===x?800:500}}>{x}</button>)}</div>}
function Empty({children}){return <div style={{...box,textAlign:"center",color:C.muted,fontSize:13}}>{children}</div>}

function Signals(){const[pair,setPair]=useState("EUR/USD"),[tf,setTf]=useState("5m"),[signal,setSignal]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const analyze=async()=>{setLoading(true);setError("");setSignal(null);try{const r=await fetch(`${API}/api/signals/analyze`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pair,timeframe:tf,user_id:TG_ID})});const d=await r.json();if(!r.ok||d.error)throw new Error(d.detail||d.error||"No signal");setSignal(d)}catch(e){setError(e.message)}finally{setLoading(false)}};
 return <><SectionTitle title="Signal Analysis" sub="Select an OTC pair and timeframe"/><Label>Currency Pair</Label><Selector value={pair} onChange={setPair} items={PAIRS}/><div style={{height:14}}/><Label>Timeframe</Label><Selector value={tf} onChange={setTf} items={TFS}/><button style={{...button,width:"100%",margin:"18px 0 14px",opacity:loading?.6:1}} onClick={analyze} disabled={loading}>{loading?"⏳ Analyzing...":"⚡ Analyze Market"}</button>{error&&<div style={{...box,color:C.red,borderColor:C.red,marginBottom:10}}>{error}</div>}{signal&&<SignalCard s={signal}/>}</>}

function VIP(){const[items,setItems]=useState([]),[loading,setLoading]=useState(true);const load=useCallback(async()=>{try{const r=await fetch(`${API}/api/signals/vip?limit=20`);const d=await r.json();setItems(Array.isArray(d)?d:[])}catch{setItems([])}finally{setLoading(false)}},[]);useEffect(()=>{load();const id=setInterval(load,30000);return()=>clearInterval(id)},[load]);return <><SectionTitle title="VIP Signals" sub="Only high-confidence setups ≥ 80%"/>{loading?<Empty>Loading VIP signals…</Empty>:items.length?items.map(s=><SignalCard key={s.id} s={s}/>):<Empty>No VIP signals yet. The scanner publishes only confirmed strategy setups.</Empty>}</>}

function Market(){const[pair,setPair]=useState("EUR/USD"),[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState("");const run=async()=>{setLoading(true);setError("");try{const r=await fetch(`${API}/api/market/analysis?pair=${encodeURIComponent(pair)}`);const d=await r.json();if(!r.ok)throw new Error(d.detail||"Market data unavailable");setData(d)}catch(e){setError(e.message);setData(null)}finally{setLoading(false)}};return <><SectionTitle title="Market AI" sub="Multi-timeframe analysis of the selected OTC pair"/><Label>Currency Pair</Label><Selector value={pair} onChange={setPair} items={PAIRS}/><button style={{...button,width:"100%",margin:"18px 0 14px"}} onClick={run}>{loading?"Analyzing…":"📈 Analyze Pair"}</button>{error&&<div style={{...box,color:C.red,borderColor:C.red}}>{error}</div>}{data&&<div style={box}><h3 style={{margin:"0 0 12px"}}>{data.pair}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(2,1fr)",gap:8}}>{Object.entries(data.timeframes||{}).map(([tf,v])=><div key={tf} style={{background:C.card2,borderRadius:10,padding:10}}><div style={{fontSize:11,color:C.muted}}>{tf}</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:4}}><Badge direction={v.direction}/><b>{v.confidence}%</b></div></div>)}</div><div style={{display:"flex",gap:8,flexWrap:"wrap",marginTop:12}}>{Object.entries(data.indicators||{}).map(([k,v])=><Pill key={k}>{k}: {v}</Pill>)}</div></div>}</>}

function Settings(){const[settings,setSettings]=useState({vip_enabled:true,notification_frequency:"standard",signal_mode:"vip"}),[saved,setSaved]=useState(false);useEffect(()=>{if(!TG_ID)return;fetch(`${API}/api/settings/user/${TG_ID}`).then(r=>r.json()).then(setSettings).catch(()=>{})},[]);const patch=async(next)=>{setSettings(next);setSaved(false);if(!TG_ID)return;try{const r=await fetch(`${API}/api/settings/user/${TG_ID}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(r.ok){setSettings(await r.json());setSaved(true);setTimeout(()=>setSaved(false),1600)}}catch{}};return <><SectionTitle title="Settings" sub={TG_ID?`Telegram ID: ${TG_ID}`:"Open inside Telegram to persist settings"}/><div style={box}>
 <Row label="VIP notifications" desc="Receive VIP alerts"><Toggle value={settings.vip_enabled} onChange={v=>patch({...settings,vip_enabled:v})}/></Row>
 <Label>Notification Frequency</Label><Selector value={settings.notification_frequency} onChange={v=>patch({...settings,notification_frequency:v})} items={["rarely","standard","often"]}/><div style={{height:16}}/><Label>Signal Mode</Label><Selector value={settings.signal_mode} onChange={v=>patch({...settings,signal_mode:v})} items={["all","vip","mixed"]}/>{saved&&<div style={{color:C.green,fontSize:12,marginTop:12}}>✓ Saved</div>}
 </div></>}

function Stats(){const[stats,setStats]=useState(null),[history,setHistory]=useState([]);useEffect(()=>{fetch(`${API}/api/stats/summary`).then(r=>r.json()).then(setStats).catch(()=>{});fetch(`${API}/api/signals/history?limit=20`).then(r=>r.json()).then(d=>setHistory(Array.isArray(d)?d:[])).catch(()=>{})},[]);const cards=[['Winrate',stats?.winrate!=null?`${stats.winrate}%`:'—',C.green],['VIP Winrate',stats?.vip_winrate!=null?`${stats.vip_winrate}%`:'—',C.gold],['Signals',stats?.total??history.length,C.accent],['VIP',stats?.vip_total??'—',C.accent2]];return <><SectionTitle title="Statistics" sub="Resolved signals and online ML performance"/><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,marginBottom:14}}>{cards.map(([l,v,c])=><div key={l} style={{...box,textAlign:"center"}}><div style={{fontSize:11,color:C.muted,textTransform:"uppercase"}}>{l}</div><div style={{fontSize:25,fontWeight:900,color:c,marginTop:5}}>{v}</div></div>)}</div><div style={box}><Label>Last 20 Signals</Label>{history.length?history.map(s=><div key={s.id} style={{display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:`1px solid ${C.border}`,padding:"8px 0"}}><div><b style={{fontSize:13}}>{s.pair}</b> <Badge direction={s.direction}/></div><div style={{fontSize:12,color:s.result==="WIN"?C.green:s.result==="LOSS"?C.red:C.muted}}>{s.confidence}% · {s.result}</div></div>):<div style={{color:C.muted,fontSize:13}}>No history yet.</div>}</div></>}

function Toggle({value,onChange}){return <button onClick={()=>onChange(!value)} style={{width:44,height:24,borderRadius:20,border:0,background:value?C.accent2:C.card2,padding:3}}><span style={{display:"block",width:18,height:18,borderRadius:"50%",background:"white",transform:`translateX(${value?20:0}px)`,transition:".2s"}}/></button>}
function Row({label,desc,children}){return <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",paddingBottom:14,marginBottom:14,borderBottom:`1px solid ${C.border}`}}><div><b>{label}</b><div style={{fontSize:11,color:C.muted}}>{desc}</div></div>{children}</div>}
function Label({children}){return <div style={{fontSize:11,color:C.accent,textTransform:"uppercase",letterSpacing:1,marginBottom:7}}>{children}</div>}
function SectionTitle({title,sub}){return <div style={{marginBottom:16}}><div style={{fontSize:20,fontWeight:900}}>{title}</div><div style={{fontSize:12,color:C.muted,marginTop:3}}>{sub}</div></div>}
const tabs=[['signals','Signals','📡'],['vip','VIP','🔥'],['market','Market AI','📈'],['settings','Settings','⚙️'],['stats','Stats','📊']];
export default function App(){const[tab,setTab]=useState('vip');useEffect(()=>{TG?.ready();TG?.expand();try{TG?.disableVerticalSwipes?.()}catch{}},[]);return <div style={{minHeight:'100vh',background:C.bg,color:C.text,fontFamily:"-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif",paddingBottom:74}}><header style={{position:'sticky',top:0,zIndex:10,display:'flex',alignItems:'center',gap:10,padding:'13px 16px',background:`linear-gradient(135deg,${C.bg},${C.card})`,borderBottom:`1px solid ${C.border}`}}><div style={{width:34,height:34,borderRadius:10,display:'grid',placeItems:'center',background:`linear-gradient(135deg,${C.accent2},${C.accent})`}}>⚡</div><div><b>AlphaPulse</b><div style={{fontSize:10,color:C.accent,textTransform:'uppercase',letterSpacing:1}}>AI Forex Engine</div></div><div style={{marginLeft:'auto',fontSize:11,color:C.green,border:`1px solid rgba(0,229,160,.3)`,borderRadius:20,padding:'3px 9px'}}>● LIVE</div></header><main style={{padding:'16px'}}>{tab==='signals'&&<Signals/>}{tab==='vip'&&<VIP/>}{tab==='market'&&<Market/>}{tab==='settings'&&<Settings/>}{tab==='stats'&&<Stats/>}</main><nav style={{position:'fixed',left:0,right:0,bottom:0,zIndex:20,display:'flex',background:C.bg,borderTop:`1px solid ${C.border}`,padding:'7px 0 10px'}}>{tabs.map(([id,label,icon])=><button key={id} onClick={()=>setTab(id)} style={{flex:1,border:0,background:'none',color:tab===id?C.accent:C.muted,opacity:tab===id?1:.55,fontSize:10,fontWeight:tab===id?800:500}}><span style={{display:'block',fontSize:18,marginBottom:2}}>{icon}</span>{label}</button>)}</nav></div>}
